### ISSUE TITLE
elisp-style `var-quoting' breaks markdown doc

### ISSUE THREAD

**Issue by NateEag** [thomas11/md-readme#6]
I've been happily using `md-readme` for [skewer-reload-stylesheet's readme](https://github.com/NateEag/skewer-reload-stylesheets/blob/master/README.md).

However, I just noticed an impedance mismatch between quoting variable names in comments and Markdown's syntax, which you can [see here](https://github.com/NateEag/skewer-reload-stylesheets/blob/master/README.md#setup).

In Markdown, backticks are paired, while in elisp, backticks are paired with single quote, resulting in the wrong highlighting you see in the third paragraph of the above-linked section.

I've come to use backtick-quoted varnames in elisp comments because they get syntax-colored correctly, and you can jump directly to their definition when using [elisp-slime-nav-mode](https://github.com/purcell/elisp-slime-nav).

[The original Markdown description](http://daringfireball.net/projects/markdown/syntax#code) and the [CommonMark spec](http://spec.commonmark.org/0.26/#fenced-code-blocks) say you can escape leading backticks like this: ``` `` `var-name' `` ```, and as you can see, it works in GitHub's Markdown parser, yielding `` `var-name' ``.

So, it looks to me like the thing to do is to search-and-replace `` `backtick-quoted-names' `` with ``` `` `backtick-quoted-names' `` ``` when rendering the document.

Thoughts?

**Comment by thomas11** [comment]
Hey Nate, sorry for getting back to you so late.

Your proposal seems fine. Not sure when I would get around to implementing it - I'd be happy about a pull request.

Thanks for using md-readme!
